# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GET_RF_MAT_NO_LOD <- function(seqnum, nmrk, CC, CR, RC, RR, minLOD, maxRF) {
    .Call('onemap_GET_RF_MAT_NO_LOD', PACKAGE = 'onemap', seqnum, nmrk, CC, CR, RC, RR, minLOD, maxRF)
}

READ_OUTCROSS <- function(file) {
    .Call('onemap_READ_OUTCROSS', PACKAGE = 'onemap', file)
}

CCOUNT <- function(X, sequence) {
    .Call('onemap_CCOUNT', PACKAGE = 'onemap', X, sequence)
}

