# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GET_RF_MAT_NO_LOD <- function(seqnum, nmrk, CC, CR, RC, RR, minLOD, maxRF) {
    .Call(`_BatchMap_GET_RF_MAT_NO_LOD`, seqnum, nmrk, CC, CR, RC, RR, minLOD, maxRF)
}

READ_OUTCROSS <- function(file) {
    .Call(`_BatchMap_READ_OUTCROSS`, file)
}

CCOUNT <- function(X, sequence) {
    .Call(`_BatchMap_CCOUNT`, X, sequence)
}

